version: "3"
    
volumes:
    volume-mariaDB:
    
services:
    db:
        image: mariadb:10.7.1-focal
        container_name: french-buy-DB
        ports:
          - 3306:3306
        volumes:
            - volume-mariaDB:/var/lib/maridb/data
        environment:
            MARIADB_USER: u8inf422
            MARIADB_PASSWORD: ThisBePassword
            MARIADB_DATABASE: u8inf422
        restart: always
        
    french-buy-logic:
        build: ./spring
        container_name: french-buy-logic
        environment:
            - DB_HOST=localhost
            - DB_USER=u8inf422
            - DB_PASSWORD=ThisBePassword
            - DB_PORT=3306
            - DB_NAME=u8inf422
        ports:
            - 8080:8080
        links:
            - db
        depends_on:
            - db
        
    french-buy-ui:
        build: ./angulars
        container_name: french-buy-ui
        links:
            - french-buy-logic
        depends_on:
            - french-buy-logic
        ports:
            - 4200:4200